### PR TITLE
Configs fonts logos reorganization

### PR DESCRIPTION
**Pull request by stripwax**
Main change here is to reduce a lot of duplicated lines from all the userconfig files, and make it slightly easier to use and add new fonts and logos.  Rather than everything in one file, and needing to know which #defines to use, simply make one file for each font or logo and make the #define equal to the filename.
Also added a variant of STM32 so that more builds are done by github actions

### CODE REVIEW

**Comment by rcmolina** [comment]
Please, check Platformio automatic building, it throwed errors.
After this, did with Arduino IDE, and have to change extension for fonts and logos to h , correct building for Arduino Pro mini and old STM32 Maple mini package with no errors.

**Comment by stripwax** [comment]
Hm, that seems odd, everything built fine for me with platformio locally,
Arduino IDE also. shouldn't need any additional changes or fixes.
I'll take a look

**Comment by stripwax** [comment]
I can't reproduce the problem you described.  I wonder why this works for
me and not you, it is very strange.
You should not need to change the .txt to .h
What errors did you get?

**Comment by stripwax** [comment]
Linking this to the following issue thread:
https://github.com/rcmolina/MaxDuino/issues/65

**Comment by stripwax** [comment]
Ah ok
Here's my platform io build on github - which passed:
https://github.com/stripwax/MaxDuino/actions/runs/12343895865
It came from this commit: https://github.com/stripwax/MaxDuino/commit/8f58fad9342bbe88e8de225ab48ce98bb7768c1a

Here's your platform io build on github - which failed:
https://github.com/rcmolina/MaxDuino/actions/runs/12347148773

The only build failure was:
Nano328p_CF7                       FAILED    00:00:01.335
(here's the full output from platformio:
```
seeed_xiao                         SUCCESS   00:00:30.750
Nano328p                           SUCCESS   00:00:11.934
Nano328p_LCD16                     SUCCESS   00:00:03.822
Nano328p_CF0                       SUCCESS   00:00:03.651
Nano328p_CF1                       SUCCESS   00:00:03.587
Nano328p_CF2                       SUCCESS   00:00:03.648
Nano328p_CF3                       SUCCESS   00:00:03.644
Nano328p_CF4                       SUCCESS   00:00:03.588
Nano328p_CF5                       SUCCESS   00:00:03.610
Nano328p_CF6                       SUCCESS   00:00:03.635
Nano328p_CF7                       FAILED    00:00:01.335
Nano328p_CF8                       SUCCESS   00:00:03.576
Nano328p_CF9                       SUCCESS   00:00:03.544
Nano328p_New                       SUCCESS   00:00:03.716
megaatmega2560_MegaDuino           SUCCESS   00:00:03.761
ThinaryNanoEvery_MaxduinoUltimate  SUCCESS   00:00:08.123
ESP8266                            SUCCESS   00:00:37.927
ESP32C3                            SUCCESS   00:00:46.433
STM32_MapleMiniDuino               SUCCESS   00:00:15.743
STM32_MapleMiniDuino_CF0           SUCCESS   00:00:07.610
```
https://github.com/rcmolina/MaxDuino/actions/runs/12347148773/job/34453801727)


You didn't need to make all those other changes
Can you revert them all and go back to what I provided in my pull request?


To fix the one failure, it's very simple, because there's one small typo here:

```
In file included from MaxDuino/Display.cpp:5:0:
MaxDuino/Logos.h:60:1: fatal error: logos/128x64/logo_MaxDuino7.txt: No such file or directory
```

It's caused by this line in the platformio.ini file. This is the test for the -DLOGO flag!
```
	-DLOGO=MaxDuino7
```

The only reason it failed is because it is named as Maxduino7 (without the case change) in the github repo.
So it's actually a really easy fix, but I need you to undo all your other changes please

image

**Comment by stripwax** [comment]
I'll produce a new pull request that backs out those changes and fixes the small typo, which should sort this out for you

**Comment by rcmolina** [comment]
@stripwax, my urderstanding iabout changing .txt to .h:
1) ide 1.8.4 throwed an error for not found file. I moved this to root dir and got also not found ( suspect it tries to add a .h?
2) Changed ext to .h ald building ok.
3) Moved back to previous dir., forcing to load explicit name
4) Changed all files extensions and thevsketch built ok.

**Comment by stripwax** [comment]
Here's the pull request that fixes the typo in platformio.ini 
https://github.com/rcmolina/MaxDuino/pull/72

and here's the platforrmio build that passed with this:
https://github.com/stripwax/MaxDuino/actions/runs/12354098374

Do we want to support IDE 1.8.4 still?
If so, then maybe your changes are required too, I have only tested latest IDE, latest packages, etc etc.

**Comment by stripwax** [comment]
Actually if you still have the exact error message you have from IDE 1.8.4, with the line number and which file was not found, etc, then I'll be able to understand more clearly.  I can try myself to retry with IDE 1.8.4 some other time, as I feel that's not a priority?

**Comment by stripwax** [comment]
Ok I tried 1.8.19 and I see the same problem.  I'm a bit surprised but ok, I guess Arduino IDE recursively copies **some** files to the temporary folder but not all of them;  because I can see in the temp build folder that it has copied all the .cpp and recursively copies all the .h from the fonts/logos folder, and ignores all the other files.  That's sortof unexpected.

The problem with calling these .h is that these are not valid C syntax.

If we must support old Arduino IDE then your change makes sense (I'll review it one more time), and I'll prepare a different feature branch with just the fix

**Comment by rcmolina** [comment]
Yes please .. I like supporting old things ( I still use an old Aspire short of free space) for Arduino testing.

**Comment by stripwax** [comment]
Ok, I see you already changed platformio.ini in a different way (you changed MaxDuino7 to cablemax, and then you commented it out).  I'm not sure what you want.  It looks like I don't need to change anything then.

**Comment by stripwax** [comment]
But I would strongly suggest reinstating -DLOGO in that config file, instead of commenting it out.  That way, the -DLOGO feature is being tested by the automatic builds.  If it's commented out, nothing is testing that it works

**Comment by rcmolina** [comment]
@stripwax , just playing to check if thev problem was related with an specific file or with de option. .. and the option was the winner. So I reverted but commented just for a working building. Once you fixed it, you should uncomment it in the new pull request.

**Comment by stripwax** [comment]
I think you've already fixed it and there's nothing left for me to do  :-)
 but I'll create a new pull request anyway with a small tidy up

**Pull request merged**
