### PR TITLE
Revert "Sdfat use improved api"

### PR DESCRIPTION
**Pull request by rcmolina**
Reverts rcmolina/MaxDuino#16

I must check more slowly, empty files showing.

### CODE REVIEW

**Comment by stripwax** [comment]
Yep, as mention I haven't completed this fully (hence why I tagged it as
draft status).  Needs verifying and testing.

**Comment by stripwax** [comment]
No concerns from me!  After you merge this to your master branch, I'll prepare an updated version of my "sdfat use improved api" branch, and do testing with sdfat 1.1.4

**Comment by rcmolina** [comment]
Thanks David,

Now only remain one branch an renamed to master.

I've double checked sdfat library version using 1.1.0

Kind regards,

Rafa

**Comment by rcmolina** [comment]
Hi David,

Happy monday.. Forgive me, I'm not very used to github funcionalities...
After reversing sdfat pulling request, I had to manually restore some of
the changes. Al so I used my own pull-request when deleting ol code, and
after performed some changes to double dirs from 3 to 6 ad file length.

I've checked the open function in your code, I'm not sure i the work also
with 8+3 names. I cpuldn't get any aot he procedires (seefile , for example
to work correcly)...

So, do you want me to remove the old master branch to continue wth actual
development? I've also made some changes to the zx81 a polarity. Removing
the branch tis also cancel the pull request.

 Let me know.

-
Rafa
-
Rafa

**Comment by stripwax** [comment]
Hm... I'm not sure I quite understand.
Usually there's only one master branch. What does "the old master branch"
mean?
Last time I checked, all the changes in the master branch looked right (and
this was working). Let me know what the problem is though please, in
particular with 8.3 filenames? (my changes remove entirely the need to use
filenames to open files, using the file number instead, so I'm confused
about the problem you described).

**Comment by stripwax** [comment]
Oh apologies, I received this via email and just realised it was a response
on a very old ticket. Maybe nothing to do but I will check.

**Comment by stripwax** [comment]
Yep I'm looking at the master branch right now, it looks correct, it has all my changes.
I don't think you need to change anything, or remove anything.
Please let me know what you think is the problem with the open function.

**Pull request closed without merging**
