### PR TITLE
Small tidy up, just moving the #include and uncommenting the -DLOGO line

### PR DESCRIPTION
**Pull request by stripwax**

### CODE REVIEW

**Review by rcmolina — APPROVED** [review]

**Comment by rcmolina** [comment]
After Merged failed, I updated version.h in the root dir (was growing ... until 120k now). I replaced this file with the one inside the source subdir,, and now the pull request was success ¿?
Some logic should be cheched ... Not sure if now automatic build is working.

**Comment by stripwax** [comment]
You should be able to click on the GitHub Actions to check if automatic
build succeeds or fails. An email is sent out when it succeeds and also
when it fails, I think. I don't know what the merge failure means here but
I can have a look tonight in case you think there is a problem.

**Comment by rcmolina** [comment]
Hi David, not this time. Finally I received the success email, but I did not urderstand why this has been growing. I'll keep an eye if still growing.

**Comment by stripwax** [comment]
Oh, I see what you mean now by 'growing'.
It used to be ok e.g. from this point in time it was ok:
https://github.com/rcmolina/MaxDuino/commit/dc1a560be8a4f6a8110199387ce357b97ab51163

But then something went wrong later:
https://github.com/rcmolina/MaxDuino/commit/5751fafec9340c02e7b517a12870e529b084ccca

and after that it started going crazy:
https://github.com/rcmolina/MaxDuino/commit/2e75ef71abb2f69540439bc6db7becc36ceb6b73

I wasn't aware.  From the history page though it seems to have happened
after the merge of my platformio branch, which is very strange:
https://github.com/rcmolina/MaxDuino/commits/master/version.h
I wonder if I accidentally moved it to the subfolder and that's what
started the problems.  Should be an easy fix, I'll get to it later tonight.

**Comment by stripwax** [comment]
Ok that's exactly what happened, my bad.  New PR in a moment.

**Pull request merged**
